title: Cayman theme
description: Hi! I am majoring in Computer Science at Vanderbilt University. I am very excited to bring my strong programming and collaboration skills, interdisciplinary interests and experiences, and–most importantly–passion for solving real-world problems using technology.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
